# Generated by Django 4.1.6 on 2023-03-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='Student Slug'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='Slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='Tutor slug'),
        ),
    ]
