# Generated by Django 4.1.6 on 2023-03-28 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0005_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorapp.tutor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorapp.client')),
            ],
        ),
    ]
