# Generated by Django 4.1.6 on 2023-03-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0006_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user',
            new_name='student',
        ),
    ]
