# Generated by Django 4.1.6 on 2023-03-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0007_rename_user_request_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestDemo',
        ),
    ]
