# Generated by Django 4.1.6 on 2023-03-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0008_rename_request_requestdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdemo',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='requestdemo',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
