# Generated by Django 4.1.6 on 2023-04-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0012_bookclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclass',
            name='amount',
        ),
    ]
