# Generated by Django 4.1.6 on 2023-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0013_remove_bookclass_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclass',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
