# Generated by Django 4.1.6 on 2023-04-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0015_democompleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoCompleted',
        ),
    ]
