# Generated by Django 4.1.6 on 2023-04-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0016_delete_democompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclass',
            name='is_complete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='requestdemo',
            name='is_complete',
            field=models.BooleanField(null=True),
        ),
    ]
