# Generated by Django 4.1.6 on 2023-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0017_bookclass_is_complete_requestdemo_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclass',
            name='amount',
        ),
    ]
