# Generated by Django 4.1.6 on 2023-04-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorapp', '0018_remove_bookclass_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=15)),
                ('standard', models.CharField(max_length=10, null=True)),
                ('tutor', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
    ]
